// Code generated by Kitex v0.12.3. DO NOT EDIT.

package nasfish

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	nas_fish "github.com/nas-studying/idl_gen/kitex_gen/nas_fish"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SignUp(ctx context.Context, req *nas_fish.SignUpReq, callOptions ...callopt.Option) (r *nas_fish.SignUpResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNasFishClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNasFishClient struct {
	*kClient
}

func (p *kNasFishClient) SignUp(ctx context.Context, req *nas_fish.SignUpReq, callOptions ...callopt.Option) (r *nas_fish.SignUpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignUp(ctx, req)
}
