// Code generated by Kitex v0.12.3. DO NOT EDIT.
package nasfish

import (
	server "github.com/cloudwego/kitex/server"
	nas_fish "github.com/nas-studying/idl_gen/kitex_gen/nas_fish"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler nas_fish.NasFish, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler nas_fish.NasFish, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
