// Code generated by Kitex v0.12.3. DO NOT EDIT.

package pptuserservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	ppt_user_service "github.com/nas-studying/idl_gen/kitex_gen/ppt_user_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AdminAuthLogin(ctx context.Context, req *ppt_user_service.AdminAuthLoginReq, callOptions ...callopt.Option) (r *ppt_user_service.AdminAuthLoginResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPPTUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPPTUserServiceClient struct {
	*kClient
}

func (p *kPPTUserServiceClient) AdminAuthLogin(ctx context.Context, req *ppt_user_service.AdminAuthLoginReq, callOptions ...callopt.Option) (r *ppt_user_service.AdminAuthLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminAuthLogin(ctx, req)
}
