// Code generated by Kitex v0.12.3. DO NOT EDIT.

package pptuserservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ppt_user_service "github.com/nas-studying/idl_gen/kitex_gen/ppt_user_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AdminAuthLogin": kitex.NewMethodInfo(
		adminAuthLoginHandler,
		newPPTUserServiceAdminAuthLoginArgs,
		newPPTUserServiceAdminAuthLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	pPTUserServiceServiceInfo                = NewServiceInfo()
	pPTUserServiceServiceInfoForClient       = NewServiceInfoForClient()
	pPTUserServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pPTUserServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pPTUserServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pPTUserServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PPTUserService"
	handlerType := (*ppt_user_service.PPTUserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ppt_user_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func adminAuthLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ppt_user_service.PPTUserServiceAdminAuthLoginArgs)
	realResult := result.(*ppt_user_service.PPTUserServiceAdminAuthLoginResult)
	success, err := handler.(ppt_user_service.PPTUserService).AdminAuthLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPPTUserServiceAdminAuthLoginArgs() interface{} {
	return ppt_user_service.NewPPTUserServiceAdminAuthLoginArgs()
}

func newPPTUserServiceAdminAuthLoginResult() interface{} {
	return ppt_user_service.NewPPTUserServiceAdminAuthLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AdminAuthLogin(ctx context.Context, req *ppt_user_service.AdminAuthLoginReq) (r *ppt_user_service.AdminAuthLoginResp, err error) {
	var _args ppt_user_service.PPTUserServiceAdminAuthLoginArgs
	_args.Req = req
	var _result ppt_user_service.PPTUserServiceAdminAuthLoginResult
	if err = p.c.Call(ctx, "AdminAuthLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
