// Code generated by Kitex v0.12.3. DO NOT EDIT.
package pptuserservice

import (
	server "github.com/cloudwego/kitex/server"
	ppt_user_service "github.com/nas-studying/idl_gen/kitex_gen/ppt_user_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler ppt_user_service.PPTUserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler ppt_user_service.PPTUserService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
